name: Main

on:
  push:
  workflow_call:
    inputs:
      dry-run:
        type: boolean
        default: false

jobs:
  dry:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ !inputs.dry-run }}
        run: echo Wet run!
      - if: ${{ inputs.dry-run }}
        run: echo Dry run!