name: Main

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Get metadata
      #   id: meta
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: hello/world
      #     tags: |
      #       type=semver,pattern={{version}}
      #       type=semver,pattern={{major}}
      # - name: Echo version
      #   run: |
      #     echo "TAG: ${{ steps.meta.outputs.tags }}"
      # - name: Get tag
      #   run: |
      #     export TAGS=${GITHUB_REF/refs\/tags\//}
      #     export SEMVER=${TAGS:1}
      #     echo "TAGS=${SEMVER}" >> $GITHUB_ENV
      # - name: Echo tag
      #   run: echo ${{ env.TAGS }}
      - run: npm install -g yarn
      - name: Does yarn here?
        run: which yarn
      - run: ls /usr/local/lib/node_modules
      - run: ls /usr/local/lib/node_modules/yarn
      - run: ls /usr/local/lib/node_modules/yarn/bin