name: Blocc CLI setup

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - name: Setup blocc
      uses: stacc/setup-blocc-cli@main
    - name: Print version
      run: |
        blocc --version
