name: Main

on:
  push:
  workflow_call:
    inputs:
      dry-run:
        type: boolean
        default: true

jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - id: version
        run: echo "version=v1.2.3" >> $GITHUB_OUTPUT
  rewrite-version:
    runs-on: ubuntu-latest
    needs: set-version
    steps:
      - name: Print version
        run: echo ${{ needs.set-version.outputs.version }}
      - name: Export version
        run: export VERSION=${{ needs.set-version.outputs.version }}
      - name: Remove prefix
        run: echo ${VERSION#v}
      - if: ${{ !inputs.dry-run }}
        run: echo Wet run!
      - if: ${{ inputs.dry-run }}
        run: echo Dry run!
