name: Test stuff

on:
  release:
    types: [published]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            make-testing-workflows-easier-pls
          tags: |
            type=semver,pattern={{version}}

