name: PR approved and labeled

on:
  push:
    branches:
      - main

jobs:
  version:
    uses: stacc/github-workflow-actions/.github/workflows/reusable_report-approval.yaml@ci/report-approval
    secrets:
      kosli-token: not-used
      github-token: ${{ github.token }}
    with:
      name: not-used
      dry-run: true
      sha256: not-used
      kosli-pipeline: not-used
