name: Main

on:
  push:

jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      dry-run: ${{ steps.version.outputs.dry-run }}
    steps:
      - id: version
        run: echo "version=v1.2.3" >> $GITHUB_OUTPUT
      - run: echo "dry-run=true" >> $GITHUB_OUTPUT
  rewrite-version:
    runs-on: ubuntu-latest
    needs: set-version
    steps:
      - name: Print version
        run: echo ${{ needs.set-version.outputs.version }}
      - name: Export version
        run: export VERSION=${{ needs.set-version.outputs.version }}
      - name: Remove prefix
        run: echo ${VERSION#v}
      - if: ${{ !needs.set-version.outputs.dry-run }}
        run: echo Wet run!
