name: Main

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: hello/world
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
      - name: Echo version
        run: |
          echo "TAG: ${{ steps.meta.outputs.tags }}"
      - name: Hmm
        run: echo "EOL"
      - name: Get tag
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Echo tag
        run: echo ${{ env.TAG }}
      - name: Echo tag without v
        run: echo ${{ env.TAG:1 }}