name: Main

on:
  push:

jobs:
  update-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Validate latest branch exists
        run: |
          (git show-branch latest &>/dev/null) && (git checkout latest) || (git checkout -b latest)
      - name: Mark latest release as using git branch
        run: git branch --force latest ${{ github.sha }} && git push --force origin latest
  update-latest-new:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Validate latest branch exists
        run: |
          (git show-branch latest-new &>/dev/null) && (git checkout latest-new) || (git checkout -b latest-new)
      - name: Mark latest release as using git branch
        run: git rebase ${{ github.sha }} && git push -f origin latest-new
