name: Main

on:
  push:

jobs:
  set-version:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "VERSION=v1.2.3" >> $GITHUB_OUTPUT
  rewrite-version:
    runs-on: ubuntu-latest
    needs: set-version
    steps:
      - name: Remove prefix
        run: echo ${${{ needs.set-version.outputs.VERSION }}#v}
